version: "3"
services:
  db:
    image: postgres:latest
    container_name: db_cont
    environment:
      POSTGRES_USER: bookmylab
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: bookmylabdb
      DATABASE_HOST: db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bookmylab.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db
    ports:
      - "5050:80"
    restart: unless-stopped
volumes:
  db_data:
 